# Notebook Python

Instalacion de pandas

In [5]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.Collecting pandas

  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.1
    Uninstalling python-dateutil-2.8.1:
      Successfully uninstalled python-dateutil-2.8.1


distutils: c:\Users\cross\AppData\Local\Programs\Python\Python39\Include\UNKNOWN
sysconfig: c:\Users\cross\AppData\Local\Programs\Python\Python39\Include
user = False
home = None
root = None
prefix = None
distutils: c:\Users\cross\AppData\Local\Programs\Python\Python39\Include\UNKNOWN
sysconfig: c:\Users\cross\AppData\Local\Programs\Python\Python39\Include
user = False
home = None
root = None
prefix = None
You should consider upgrading via the 'c:\Users\cross\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


#Instalacion numpy

In [6]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


distutils: c:\Users\cross\AppData\Local\Programs\Python\Python39\Include\UNKNOWN
sysconfig: c:\Users\cross\AppData\Local\Programs\Python\Python39\Include
user = False
home = None
root = None
prefix = None
distutils: c:\Users\cross\AppData\Local\Programs\Python\Python39\Include\UNKNOWN
sysconfig: c:\Users\cross\AppData\Local\Programs\Python\Python39\Include
user = False
home = None
root = None
prefix = None
You should consider upgrading via the 'c:\Users\cross\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


#arreglos

In [8]:
import numpy as np

arreglo1= np.array([1,2,3]) #Son arreglos unidimensionales de 3 numeros o 3 caracteres

print(arreglo1)

arreglo2=np.array([4,5,6])

print(arreglo2)



[1 2 3]
[4 5 6]


In [12]:
arreglo1= np.array(([1,2,3], [4,5,6])) #Se deben poner parentesis dobles cuando son 2 listas para arreglos

print(arreglo1)

arreglo2= np.array((([1,2,3], [4,5,6], [7,8,9])))

print(arreglo2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
arr= np.array([1,2,3,4,5,6], ndmin= 3)#ndim es el numero de dimensiones

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [18]:
arr2= np.zeros((2,2)) #arreglo de ceros

print(arr2)

[[0. 0.]
 [0. 0.]]


In [19]:
arr3=np.ones((3,3))

print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
arr4=np.random.rand(3,3) #un arreglo entre valores numericos entre 0 y el 1

print(arr4)

[[0.85337752 0.53409287 0.86391061]
 [0.13718428 0.79849633 0.53422294]
 [0.96028207 0.72471374 0.27009394]]


#Operaciones

In [22]:
arr1= [1,2,3]

arr2 = [4,5,6]

arr3= np.add(arr1, arr2) #con la funcion "add" podemos sumar arreglos esta es la suma de los numeros de los dos arreglos

print(arr3)

[5 7 9]


In [24]:
arr1= [1,2,3]

arr2 = [4,5,6]

arr3= np.subtract(arr2, arr1) #con la funcion "subtract" podemos restar arreglos esta es la suma de los numeros de los dos arreglos

print(arr3)

[3 3 3]


In [25]:
arr1= [1,2,3]

arr2 = [4,5,6]

arr3= np.multiply(arr1, arr2) #con la funcion "multiply" podemos multiplicar arreglos esta es la suma de los numeros de los dos arreglos

print(arr3)

[ 4 10 18]


In [26]:
arr1= [1,2,3]

arr2 = [4,5,6]

arr3= np.divide(arr1, arr2) #con la funcion "divide" podemos dividir arreglos esta es la suma de los numeros de los dos arreglos

print(arr3)

[0.25 0.4  0.5 ]


#Agregacion

In [28]:
arr= [1,6,9]

media =  np.mean(arr)

print(media)

5.333333333333333


In [29]:
arr= [1,6,9]

mediana =  np.median(arr)

print(mediana)

6.0


In [30]:
arr= [1,6,9]

maximo =  np.max(arr)

print(maximo)

9


In [31]:
arr= [1,6,9]

minimo =  np.min(arr)

print(minimo)

1


#Indexacion

In [32]:
arr =np.array([1,2,3,4,5,6])

print(arr[0])

1


In [33]:
arr =np.array([1,2,3,4,5,6])

print(arr[-1])

6


In [34]:
arr =np.array(([1,2,3], [4,5,6]))

print(arr[1, 2]) #Son coordenadas, es decir, del elemento 1 o sea el [4,5,6], el elemento 2 o sea el 6

6


#Slicing o rangos

In [35]:
arr =np.array([1,2,3,4,5,6])

print(arr[1:4]) #Recorre la lista, pero al llegar al 4 es no inclusivo es decir no imprime el 5

[2 3 4]


In [36]:
arr =np.array([1,2,3,4,5,6])

print(arr[1:4:2]) #recorre la lista al elemento 4 pero de dos en dos

[2 4]


In [37]:
arr =np.array([1,2,3,4,5,6])

print(arr[::2]) #recorre la lista pero en secuencia de numeros impares, que son de vacio a vacio.

[1 3 5]


Tipos de datos

In [42]:
import numpy as np

arr = np.array(["b", "a"]) #Este tipo es para ver el tipo de datos

print(arr.dtype) #El dato es no numerico es string

print(arr)

arr2 = np.array([1,2,3,4])

print(arr2.dtype) #Viene el dato tipo numero int32

print(arr2)

arr3 = np.array([5.4, 3.1, 2,9, 9.9])

print(arr3.dtype) #Este tipo de dato es float64

print(arr3)

<U1
['b' 'a']
int32
[1 2 3 4]
float64
[5.4 3.1 2.  9.  9.9]


In [43]:
arr =  np.array([1,2,3], dtype= "S")

#'i' = integer(entero)
#'b' = booleano
#'f' = flotante
#'M' = datetime
#'O' = objeto
#'S' = string (cadena)

print(arr)

[b'1' b'2' b'3']


In [44]:
arr = np.array([1.1, 2.1, 3.1])

print("pre", arr)

nuevo_arr =  arr.astype('i') #astype a traves de las claves del codigo de arriba nos tranforma los datos a otro tipo de dato en este caso 
                             # la letra "i" corresponde a entero, y los pasa de flotante a entero

print("post", nuevo_arr)

pre [1.1 2.1 3.1]
post [1 2 3]


Copy vs View

In [45]:
arr = np.array([1,2,3])

x= arr.copy() #Hace copia del arreglo

y= arr.view() #Hace vista o visualizacion del arreglo


print("arr", arr)
print("x", x)
print("y", y)

arr[0] = 0

print("arr", arr)
print("x", x)
print("y", y)
#Por esta razon el arreglo "y" en la segunda parte es 0,2,3 porque se modifico el arreglo original y el arreglo x se mantiene porque es una copia
#del primero.



arr [1 2 3]
x [1 2 3]
y [1 2 3]
arr [0 2 3]
x [1 2 3]
y [0 2 3]


#Concatenar

In [47]:
arr1 = np.array([1,2,3])

print("arr1", arr1)

arr2 = np.array([4,5,6])

print("arr2", arr2)

arr3 = np.concatenate((arr1, arr2)) #Concatena los arreglos, es decir los une

print("arr3", arr3)

arr1 [1 2 3]
arr2 [4 5 6]
arr3 [1 2 3 4 5 6]


busqueda

In [48]:
arr = np.array([1,2,2,4,5,5,4])

x =  np.where(arr==5) #busca el numero que estemos buscando o el indice que busquemos
                      #nos devuelve el indice del numero, en este caso hay dos 5 entonces nos devuelve 4,5 que es donde se posiciona el numero 5

print(x)

(array([4, 5], dtype=int64),)


ordenar

In [49]:
arr =  np.array([2,5,6,4,1,3])

x = np.sort(arr) #Esta funcion se parece a la funcion de python que es ordenar de menor a mayor

print(x)

[1 2 3 4 5 6]
